config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  root 'static_pages#home'

  get 'help'=>'static_pages#help'

  get 'about'=>'static_pages#about'

  get 'contact'=>'static_pages#contact'

  get 'signup'  => 'users#new'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts do
      resources :comments,            only: [:create, :destroy]
  end
  resources :relationships,       only: [:create, :destroy]

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  has_many :comments, foreign_key: "micropost_id"
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  validates :title, presence: true, length: { maximum: 140 }
  validate  :picture_size

  private
  # Validates the size of an uploaded picture.
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
	before_action :logged_in_user, only: [:create, :destroy]
	before_action :correct_user,   only: :destroy

  	def create
  		@micropost = current_user.microposts.build(micropost_params)
	    if @micropost.save
	      flash[:success] = "Micropost created!"
	      redirect_to root_url
	    # else
	    #   @feed_items = []
	    #   render 'static_pages/home'
	    end
  	end

  	def destroy
  		@micropost.destroy
	    flash[:success] = "Micropost deleted"
	    redirect_to request.referrer || root_url
  	end

  	def show
  		@microposts = Micropost.find(params[:id])
  		@user = User.find(@microposts.user_id)
  		@comments = @microposts.comments.paginate(page: params[:page], per_page: 5)

  		if logged_in?
	      @comment_new  = current_user.comments.build
	    end
    	#@microposts = @user.microposts.paginate(page: params[:page])
  	end

  	private

	    def micropost_params
      		params.require(:micropost).permit(:content, :picture, :title)
    	end

	    def correct_user
	    	@micropost = current_user.microposts.find_by(id: params[:id])
	    	redirect_to root_url if @micropost.nil?
	    end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_form.html.erb
<%= form_for(@micropost) do |f| %>
  <% if @micropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>

      <ul>
      <% @micropost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
  <span class="title">
    <%= link_to micropost.title, micropost%> <br>
  </span>

  <span class="content">

    <%= micropost.content %>
    <%= image_tag micropost.picture.url if micropost.picture? %>
    
  </span>

  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago. 
    By <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
    <% if current_user?(micropost.user) %>
      <%= link_to "delete", micropost, method: :delete,
                                       data: { confirm: "You sure?" } %>
    <% end %>
  </span>

  <div class="row">

    

      <% micropost.comments.each_with_index do |comment, index| %>
          <%= render "comments/comment", comment: comment, index: index + 1 %>
        <% end %>
      <div id="comment-new-<%=micropost.id %>"></div>

    
  </div>

  <% if logged_in? %>

    <% if current_user?(@user) || current_user.following?(@user) %>

      <div class ="content" style="padding-top:20px">
          <%= form_for @comment_new, :url => {:action=>"create", :controller=>"comments", :micropost_id=>micropost.id}, remote: true do |f| %>
            <%= render 'shared/error_messages', object: f.object %>



            <div class="field">
              <%= f.text_field :content, placeholder: "Compose new comment...", class: "form-control", 
               id: "new_comment_#{micropost.id}" %>
            </div>

            <%= f.submit "Send comment", class: "btn btn-primary" , id: "btn-submit" %>
            
          <% end %>
      </div>
    <% end %>
  <% end %>
</li>

app/views/microposts/edit.html.erb
<h1>Editing Micropost</h1>

<%= render 'form' %>

<%= link_to 'Show', @micropost %> |
<%= link_to 'Back', microposts_path %>

app/views/microposts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Microposts</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @microposts.each do |micropost| %>
      <tr>
        <td><%= micropost.content %></td>
        <td><%= micropost.user_id %></td>
        <td><%= link_to 'Show', micropost %></td>
        <td><%= link_to 'Edit', edit_micropost_path(micropost) %></td>
        <td><%= link_to 'Destroy', micropost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Micropost', new_micropost_path %>

app/views/microposts/new.html.erb
<h1>New Micropost</h1>

<%= render 'form' %>

<%= link_to 'Back', microposts_path %>

app/views/microposts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="microposts-display">
	<div class="row">
		<div class="col-md-6">
			<br>
			<div class="title"><%= @microposts.title %>
				<span class="timestamp">
				    Posted <%= time_ago_in_words(@microposts.created_at) %> ago. 
				    By <span class="user"><strong><%= link_to @microposts.user.name, @microposts.user %></strong>
				    </span>
				    <% if current_user?(@microposts.user) %>
				      <%= link_to "delete", @microposts , method: :delete,
				                                       data: { confirm: "You sure?" } %>
				    <% end %>
				</span>
			</div>
			
			<div class="content">
				<%= @microposts.content %>
				<div class="img-reponsive">
					<%= image_tag @microposts.picture.url if @microposts.picture? %>
				</div>
			</div>

			<% if logged_in? %>

				<% if current_user?(@user) || current_user.following?(@user) %>

					<div class ="comment">
						<%= render 'shared/comment_form' %>
					</div>

				<% else %>
					<span> leaving your comment? please go to <strong><%= link_to "My Profile", @microposts.user %></strong> and follow me (~_~) </span>
				<% end %>


			<% else %>
				please <%= link_to "login", login_path %> to leave your comment!

			<% end %>

		</div>
		<div class="col-lg-6">
			<h2> Comment for this Entry </h2>
			<% if @comments.any? %>

			    <div class= "microposts">
			    <% @comments.each do |comment|	%>					      
			      <li id="comment-<%= comment.id%>" class="micropost-<%= comment.micropost_id %>">
					  <div style="padding: 15px">
					    <div class="content">
					      <%= comment.content %>
					    </div>
					    <span class="timestamp">
					      Posted <%= time_ago_in_words(comment.created_at) %> ago. Comment by <span class="user"><%= link_to comment.user.name, comment.user %></span>
					    </span>
					  </div>
					</li>
					<% end %>
			    </div>

			  	<%= will_paginate @comments %>
			<% end %>
			
		</div>
	</div>
</div>